# Generated by Django 5.1.2 on 2024-10-29 16:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('extra', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='FoodItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=10)),
                ('date', models.DateField()),
                ('type', models.CharField(max_length=10)),
                ('location', models.CharField(max_length=10)),
                ('foods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ut_dining.food')),
            ],
        ),
    ]
