# Generated by Django 5.1.2 on 2024-10-29 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ut_dining', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fooditem',
            name='foods',
        ),
        migrations.AddField(
            model_name='fooditem',
            name='foods',
            field=models.ManyToManyField(to='ut_dining.food'),
        ),
    ]
